version: '3.8'

services:
  processor:
    build:
      context: .
      dockerfile: Dockerfile.processor
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ${DNJPLAYER_CACHE_DIR:-./cache}:/output
      - ./shaders:/shaders:ro
    environment:
      - INPUT_URL
      - OUTPUT_FILE
      - TARGET_W
      - TARGET_H
      - SHADER_PATH
    network_mode: host
